version: '3.4'

networks:
  default:
    driver: bridge
services:

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
    - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile

    networks:
      - default
    volumes:
      - ./app/:/app
      - ./Internship.csv:/app/Internship.csv
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    ports:
    - "8080:5000"
    env_file:
      - .env
    depends_on:
      - db
